// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7xTsZ5mxxODjaJBcg1e05TtRfNa_BzhU',
    appId: '1:663174540119:web:70a7e3c038e736a8906c12',
    messagingSenderId: '663174540119',
    projectId: 'banking-app-b8964',
    authDomain: 'banking-app-b8964.firebaseapp.com',
    storageBucket: 'banking-app-b8964.firebasestorage.app',
    measurementId: 'G-JKDJBNB5NH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8GV047LGCRmF2_VFzUZGjwnBtlf2YjT8',
    appId: '1:663174540119:android:c21246365866381d906c12',
    messagingSenderId: '663174540119',
    projectId: 'banking-app-b8964',
    storageBucket: 'banking-app-b8964.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMvZz1wQZcHptZYb0_BHyJhH7UOSO8dzQ',
    appId: '1:663174540119:ios:6ea38ac2046398d1906c12',
    messagingSenderId: '663174540119',
    projectId: 'banking-app-b8964',
    storageBucket: 'banking-app-b8964.firebasestorage.app',
    androidClientId: '663174540119-61rskhhk5sd1jb8lb4lce9pge0bdc6db.apps.googleusercontent.com',
    iosClientId: '663174540119-ll565vuge8amm6pe0atkgt9k5ldqcm0h.apps.googleusercontent.com',
    iosBundleId: 'com.example.bankingApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMvZz1wQZcHptZYb0_BHyJhH7UOSO8dzQ',
    appId: '1:663174540119:ios:6ea38ac2046398d1906c12',
    messagingSenderId: '663174540119',
    projectId: 'banking-app-b8964',
    storageBucket: 'banking-app-b8964.firebasestorage.app',
    androidClientId: '663174540119-61rskhhk5sd1jb8lb4lce9pge0bdc6db.apps.googleusercontent.com',
    iosClientId: '663174540119-ll565vuge8amm6pe0atkgt9k5ldqcm0h.apps.googleusercontent.com',
    iosBundleId: 'com.example.bankingApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7xTsZ5mxxODjaJBcg1e05TtRfNa_BzhU',
    appId: '1:663174540119:web:9c44b32530f913d5906c12',
    messagingSenderId: '663174540119',
    projectId: 'banking-app-b8964',
    authDomain: 'banking-app-b8964.firebaseapp.com',
    storageBucket: 'banking-app-b8964.firebasestorage.app',
    measurementId: 'G-K7J0JK2J7C',
  );
}
